//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenceRep.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SenceRep.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Агент.
        /// </summary>
        internal static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От кого:.
        /// </summary>
        internal static string AgentPosition {
            get {
                return ResourceManager.GetString("AgentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По агентам.
        /// </summary>
        internal static string AgentsQuota {
            get {
                return ResourceManager.GetString("AgentsQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возрастное ограничение.
        /// </summary>
        internal static string AgeRestriction {
            get {
                return ResourceManager.GetString("AgeRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В других документах работающих с ценами есть не сохраненные данные. Сохраните их или обновите документы..
        /// </summary>
        internal static string AnotherPriceEditDocumentIsEditedSaveOrRefresh {
            get {
                return ResourceManager.GetString("AnotherPriceEditDocumentIsEditedSaveOrRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество:.
        /// </summary>
        internal static string CountPosition {
            get {
                return ResourceManager.GetString("CountPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата:.
        /// </summary>
        internal static string DatePosition {
            get {
                return ResourceManager.GetString("DatePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление мероприятия.
        /// </summary>
        internal static string DeleteEvent {
            get {
                return ResourceManager.GetString("DeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить текущее мероприятие?.
        /// </summary>
        internal static string DeleteEventConfirmation {
            get {
                return ResourceManager.GetString("DeleteEventConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле не должно быть пустым.
        /// </summary>
        internal static string EmptyFieldValidationRule {
            get {
                return ResourceManager.GetString("EmptyFieldValidationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата окончания мероприятия.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Маркер &quot;Итого&quot;.
        /// </summary>
        internal static string EndTableMarker {
            get {
                return ResourceManager.GetString("EndTableMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Колонка маркера.
        /// </summary>
        internal static string EndTableMarkerColumn {
            get {
                return ResourceManager.GetString("EndTableMarkerColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите код.
        /// </summary>
        internal static string EventCode {
            get {
                return ResourceManager.GetString("EventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите время окончания.
        /// </summary>
        internal static string EventEndDate {
            get {
                return ResourceManager.GetString("EventEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите юр. лицо.
        /// </summary>
        internal static string EventLegalEntity {
            get {
                return ResourceManager.GetString("EventLegalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название мероприятия.
        /// </summary>
        internal static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мероприятие:.
        /// </summary>
        internal static string EventPosition {
            get {
                return ResourceManager.GetString("EventPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите время начала.
        /// </summary>
        internal static string EventStartDate {
            get {
                return ResourceManager.GetString("EventStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл сконвертирован некорректно.
        /// </summary>
        internal static string File_Load_exception {
            get {
                return ResourceManager.GetString("File_Load_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл не распознан или в нём нет данных..
        /// </summary>
        internal static string File_undefined {
            get {
                return ResourceManager.GetString("File_undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл не распознан или в нём нет данных:.
        /// </summary>
        internal static string File_Undefined_Or_No_Data {
            get {
                return ResourceManager.GetString("File_Undefined_Or_No_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Родительный падеж.
        /// </summary>
        internal static string Genitive {
            get {
                return ResourceManager.GetString("Genitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зал.
        /// </summary>
        internal static string Hall {
            get {
                return ResourceManager.GetString("Hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индивидуальный предприниматель.
        /// </summary>
        internal static string IndividualEntrepreneur {
            get {
                return ResourceManager.GetString("IndividualEntrepreneur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИНН.
        /// </summary>
        internal static string INN {
            get {
                return ResourceManager.GetString("INN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только непроверенные.
        /// </summary>
        internal static string IsNotOnlyUnchecked {
            get {
                return ResourceManager.GetString("IsNotOnlyUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только для выбранного агента.
        /// </summary>
        internal static string IsOnlySelectedAgent {
            get {
                return ResourceManager.GetString("IsOnlySelectedAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КПП.
        /// </summary>
        internal static string KPP {
            get {
                return ResourceManager.GetString("KPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Юр. лицо.
        /// </summary>
        internal static string LegalEntity {
            get {
                return ResourceManager.GetString("LegalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка документа....
        /// </summary>
        internal static string LoadingDocument {
            get {
                return ResourceManager.GetString("LoadingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введён не правильный пароль.
        /// </summary>
        internal static string MainDocument_AdminRoomExecute_Введён_не_правильный_пароль {
            get {
                return ResourceManager.GetString("MainDocument_AdminRoomExecute_Введён_не_правильный_пароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответственный менеджер.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Именительный падеж.
        /// </summary>
        internal static string Nominative {
            get {
                return ResourceManager.GetString("Nominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОГРН.
        /// </summary>
        internal static string OGRN {
            get {
                return ResourceManager.GetString("OGRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОГРНИП.
        /// </summary>
        internal static string OGRNIP {
            get {
                return ResourceManager.GetString("OGRNIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действует на основании.
        /// </summary>
        internal static string OnBasis {
            get {
                return ResourceManager.GetString("OnBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (%)процент.
        /// </summary>
        internal static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Место проведения.
        /// </summary>
        internal static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа мест проведения.
        /// </summary>
        internal static string PlaceGroup {
            get {
                return ResourceManager.GetString("PlaceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Место проведения:.
        /// </summary>
        internal static string PlacePosition {
            get {
                return ResourceManager.GetString("PlacePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Положение в таблице.
        /// </summary>
        internal static string PositionInTable {
            get {
                return ResourceManager.GetString("PositionInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена:.
        /// </summary>
        internal static string PricePosition {
            get {
                return ResourceManager.GetString("PricePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Организатор.
        /// </summary>
        internal static string Promoter {
            get {
                return ResourceManager.GetString("Promoter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Увеличить.
        /// </summary>
        internal static string Raise {
            get {
                return ResourceManager.GetString("Raise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повтор....
        /// </summary>
        internal static string RedoProgress {
            get {
                return ResourceManager.GetString("RedoProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уменьшить.
        /// </summary>
        internal static string Reduce {
            get {
                return ResourceManager.GetString("Reduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В других документах работающих с ценами есть не сохраненные данные. Продолжить?.
        /// </summary>
        internal static string RePriceSeatsDocument_ShowNotification {
            get {
                return ResourceManager.GetString("RePriceSeatsDocument_ShowNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на единиц.
        /// </summary>
        internal static string RePriceViewModel_currency {
            get {
                return ResourceManager.GetString("RePriceViewModel_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Места из накладной не найдены на схеме.
        /// </summary>
        internal static string ReturnVoucherLoadDocument_LoadSeatsFromReturnEvent_Места_из_накладной_не_найдены_на_схеме {
            get {
                return ResourceManager.GetString("ReturnVoucherLoadDocument_LoadSeatsFromReturnEvent_Места_из_накладной_не_найдены_" +
                        "на_схеме", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ряд:.
        /// </summary>
        internal static string RowPosition {
            get {
                return ResourceManager.GetString("RowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение мероприятия.
        /// </summary>
        internal static string SaveEvent {
            get {
                return ResourceManager.GetString("SaveEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить изменения?.
        /// </summary>
        internal static string SaveEventConfirmation {
            get {
                return ResourceManager.GetString("SaveEventConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Схема.
        /// </summary>
        internal static string Scheme {
            get {
                return ResourceManager.GetString("Scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Схемы не существует.
        /// </summary>
        internal static string Scheme_does_not_exist {
            get {
                return ResourceManager.GetString("Scheme_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во мест.
        /// </summary>
        internal static string SeatCount {
            get {
                return ResourceManager.GetString("SeatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Места с:.
        /// </summary>
        internal static string SeatFromPosition {
            get {
                return ResourceManager.GetString("SeatFromPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип мест:.
        /// </summary>
        internal static string SeatGroupPosition {
            get {
                return ResourceManager.GetString("SeatGroupPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Места не найдены.
        /// </summary>
        internal static string Seats_not_found {
            get {
                return ResourceManager.GetString("Seats_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Места из накладной не найдены на схеме.
        /// </summary>
        internal static string Seats_not_found_on_scheme {
            get {
                return ResourceManager.GetString("Seats_not_found_on_scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Места по:.
        /// </summary>
        internal static string SeatToPosition {
            get {
                return ResourceManager.GetString("SeatToPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сектор:.
        /// </summary>
        internal static string SectorPosition {
            get {
                return ResourceManager.GetString("SectorPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите юридическое лицо.
        /// </summary>
        internal static string SelectDefaultPromoterLegalEntity {
            get {
                return ResourceManager.GetString("SelectDefaultPromoterLegalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо выбрать агента.
        /// </summary>
        internal static string SelectedAgentRequired {
            get {
                return ResourceManager.GetString("SelectedAgentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала мероприятия.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма:.
        /// </summary>
        internal static string SumPricePosition {
            get {
                return ResourceManager.GetString("SumPricePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кому:.
        /// </summary>
        internal static string SupplierPosition {
            get {
                return ResourceManager.GetString("SupplierPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время:.
        /// </summary>
        internal static string TimePosition {
            get {
                return ResourceManager.GetString("TimePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Существует неподтвержденная операция с этими местами. Подтвердите операции..
        /// </summary>
        internal static string unaccepted_operation {
            get {
                return ResourceManager.GetString("unaccepted_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Откат....
        /// </summary>
        internal static string UndoProgress {
            get {
                return ResourceManager.GetString("UndoProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операции с накладными.
        /// </summary>
        internal static string VoucherOperations {
            get {
                return ResourceManager.GetString("VoucherOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаблон накладной.
        /// </summary>
        internal static string VoucherTemplate {
            get {
                return ResourceManager.GetString("VoucherTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо выбрать шаблон накладной.
        /// </summary>
        internal static string VoucherTemplateRequired {
            get {
                return ResourceManager.GetString("VoucherTemplateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .xml.
        /// </summary>
        internal static string Xml_Extension_String {
            get {
                return ResourceManager.GetString("Xml_Extension_String", resourceCulture);
            }
        }
    }
}
