//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Styx.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Styx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агент.
        /// </summary>
        internal static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От кого:.
        /// </summary>
        internal static string AgentPosition {
            get {
                return ResourceManager.GetString("AgentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По агентам.
        /// </summary>
        internal static string AgentsQuota {
            get {
                return ResourceManager.GetString("AgentsQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возрастное ограничение.
        /// </summary>
        internal static string AgeRestriction {
            get {
                return ResourceManager.GetString("AgeRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В других документах работающих с ценами есть не сохраненные данные. Сохраните их или обновите документы..
        /// </summary>
        internal static string AnotherPriceEditDocumentIsEditedSaveOrRefresh {
            get {
                return ResourceManager.GetString("AnotherPriceEditDocumentIsEditedSaveOrRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество:.
        /// </summary>
        internal static string CountPosition {
            get {
                return ResourceManager.GetString("CountPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата:.
        /// </summary>
        internal static string DatePosition {
            get {
                return ResourceManager.GetString("DatePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление мероприятия.
        /// </summary>
        internal static string DeleteEvent {
            get {
                return ResourceManager.GetString("DeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить текущее мероприятие?.
        /// </summary>
        internal static string DeleteEventConfirmation {
            get {
                return ResourceManager.GetString("DeleteEventConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не должно быть пустым.
        /// </summary>
        internal static string EmptyFieldValidationRule {
            get {
                return ResourceManager.GetString("EmptyFieldValidationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания мероприятия.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маркер &quot;Итого&quot;.
        /// </summary>
        internal static string EndTableMarker {
            get {
                return ResourceManager.GetString("EndTableMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колонка маркера.
        /// </summary>
        internal static string EndTableMarkerColumn {
            get {
                return ResourceManager.GetString("EndTableMarkerColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите код.
        /// </summary>
        internal static string EventCode {
            get {
                return ResourceManager.GetString("EventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите время окончания.
        /// </summary>
        internal static string EventEndDate {
            get {
                return ResourceManager.GetString("EventEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите юр. лицо.
        /// </summary>
        internal static string EventLegalEntity {
            get {
                return ResourceManager.GetString("EventLegalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название мероприятия.
        /// </summary>
        internal static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мероприятие:.
        /// </summary>
        internal static string EventPosition {
            get {
                return ResourceManager.GetString("EventPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите время начала.
        /// </summary>
        internal static string EventStartDate {
            get {
                return ResourceManager.GetString("EventStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл сконвертирован некорректно.
        /// </summary>
        internal static string File_Load_exception {
            get {
                return ResourceManager.GetString("File_Load_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл не распознан или в нём нет данных..
        /// </summary>
        internal static string File_undefined {
            get {
                return ResourceManager.GetString("File_undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл не распознан или в нём нет данных:.
        /// </summary>
        internal static string File_Undefined_Or_No_Data {
            get {
                return ResourceManager.GetString("File_Undefined_Or_No_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Родительный падеж.
        /// </summary>
        internal static string Genitive {
            get {
                return ResourceManager.GetString("Genitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зал.
        /// </summary>
        internal static string Hall {
            get {
                return ResourceManager.GetString("Hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индивидуальный предприниматель.
        /// </summary>
        internal static string IndividualEntrepreneur {
            get {
                return ResourceManager.GetString("IndividualEntrepreneur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИНН.
        /// </summary>
        internal static string INN {
            get {
                return ResourceManager.GetString("INN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только непроверенные.
        /// </summary>
        internal static string IsNotOnlyUnchecked {
            get {
                return ResourceManager.GetString("IsNotOnlyUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только для выбранного агента.
        /// </summary>
        internal static string IsOnlySelectedAgent {
            get {
                return ResourceManager.GetString("IsOnlySelectedAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КПП.
        /// </summary>
        internal static string KPP {
            get {
                return ResourceManager.GetString("KPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юр. лицо.
        /// </summary>
        internal static string LegalEntity {
            get {
                return ResourceManager.GetString("LegalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка документа....
        /// </summary>
        internal static string LoadingDocument {
            get {
                return ResourceManager.GetString("LoadingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введён не правильный пароль.
        /// </summary>
        internal static string MainDocument_AdminRoomExecute_Введён_не_правильный_пароль {
            get {
                return ResourceManager.GetString("MainDocument_AdminRoomExecute_Введён_не_правильный_пароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответственный менеджер.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Именительный падеж.
        /// </summary>
        internal static string Nominative {
            get {
                return ResourceManager.GetString("Nominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОГРН.
        /// </summary>
        internal static string OGRN {
            get {
                return ResourceManager.GetString("OGRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОГРНИП.
        /// </summary>
        internal static string OGRNIP {
            get {
                return ResourceManager.GetString("OGRNIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действует на основании.
        /// </summary>
        internal static string OnBasis {
            get {
                return ResourceManager.GetString("OnBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (%)процент.
        /// </summary>
        internal static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место проведения.
        /// </summary>
        internal static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа мест проведения.
        /// </summary>
        internal static string PlaceGroup {
            get {
                return ResourceManager.GetString("PlaceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место проведения:.
        /// </summary>
        internal static string PlacePosition {
            get {
                return ResourceManager.GetString("PlacePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Положение в таблице.
        /// </summary>
        internal static string PositionInTable {
            get {
                return ResourceManager.GetString("PositionInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена:.
        /// </summary>
        internal static string PricePosition {
            get {
                return ResourceManager.GetString("PricePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организатор.
        /// </summary>
        internal static string Promoter {
            get {
                return ResourceManager.GetString("Promoter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличить.
        /// </summary>
        internal static string Raise {
            get {
                return ResourceManager.GetString("Raise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повтор....
        /// </summary>
        internal static string RedoProgress {
            get {
                return ResourceManager.GetString("RedoProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уменьшить.
        /// </summary>
        internal static string Reduce {
            get {
                return ResourceManager.GetString("Reduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В других документах работающих с ценами есть не сохраненные данные. Продолжить?.
        /// </summary>
        internal static string RePriceSeatsDocument_ShowNotification {
            get {
                return ResourceManager.GetString("RePriceSeatsDocument_ShowNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to единиц.
        /// </summary>
        internal static string RePriceViewModel_currency {
            get {
                return ResourceManager.GetString("RePriceViewModel_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Места из накладной не найдены на схеме.
        /// </summary>
        internal static string ReturnVoucherLoadDocument_LoadSeatsFromReturnEvent_Места_из_накладной_не_найдены_на_схеме {
            get {
                return ResourceManager.GetString("ReturnVoucherLoadDocument_LoadSeatsFromReturnEvent_Места_из_накладной_не_найдены_" +
                        "на_схеме", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ряд:.
        /// </summary>
        internal static string RowPosition {
            get {
                return ResourceManager.GetString("RowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение мероприятия.
        /// </summary>
        internal static string SaveEvent {
            get {
                return ResourceManager.GetString("SaveEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения?.
        /// </summary>
        internal static string SaveEventConfirmation {
            get {
                return ResourceManager.GetString("SaveEventConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Схема.
        /// </summary>
        internal static string Scheme {
            get {
                return ResourceManager.GetString("Scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Схемы не существует.
        /// </summary>
        internal static string Scheme_does_not_exist {
            get {
                return ResourceManager.GetString("Scheme_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во мест.
        /// </summary>
        internal static string SeatCount {
            get {
                return ResourceManager.GetString("SeatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Места с:.
        /// </summary>
        internal static string SeatFromPosition {
            get {
                return ResourceManager.GetString("SeatFromPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип мест:.
        /// </summary>
        internal static string SeatGroupPosition {
            get {
                return ResourceManager.GetString("SeatGroupPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Места не найдены.
        /// </summary>
        internal static string Seats_not_found {
            get {
                return ResourceManager.GetString("Seats_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Места из накладной не найдены на схеме.
        /// </summary>
        internal static string Seats_not_found_on_scheme {
            get {
                return ResourceManager.GetString("Seats_not_found_on_scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Места по:.
        /// </summary>
        internal static string SeatToPosition {
            get {
                return ResourceManager.GetString("SeatToPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сектор:.
        /// </summary>
        internal static string SectorPosition {
            get {
                return ResourceManager.GetString("SectorPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите юридическое лицо.
        /// </summary>
        internal static string SelectDefaultPromoterLegalEntity {
            get {
                return ResourceManager.GetString("SelectDefaultPromoterLegalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать агента.
        /// </summary>
        internal static string SelectedAgentRequired {
            get {
                return ResourceManager.GetString("SelectedAgentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала мероприятия.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма:.
        /// </summary>
        internal static string SumPricePosition {
            get {
                return ResourceManager.GetString("SumPricePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кому:.
        /// </summary>
        internal static string SupplierPosition {
            get {
                return ResourceManager.GetString("SupplierPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время:.
        /// </summary>
        internal static string TimePosition {
            get {
                return ResourceManager.GetString("TimePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Существует неподтвержденная операция с этими местами. Подтвердите операции..
        /// </summary>
        internal static string unaccepted_operation {
            get {
                return ResourceManager.GetString("unaccepted_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откат....
        /// </summary>
        internal static string UndoProgress {
            get {
                return ResourceManager.GetString("UndoProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операции с накладными.
        /// </summary>
        internal static string VoucherOperations {
            get {
                return ResourceManager.GetString("VoucherOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблон накладной.
        /// </summary>
        internal static string VoucherTemplate {
            get {
                return ResourceManager.GetString("VoucherTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать шаблон накладной.
        /// </summary>
        internal static string VoucherTemplateRequired {
            get {
                return ResourceManager.GetString("VoucherTemplateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xml.
        /// </summary>
        internal static string Xml_Extension_String {
            get {
                return ResourceManager.GetString("Xml_Extension_String", resourceCulture);
            }
        }
    }
}
