//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Styx.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Styx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Activate_32 {
            get {
                object obj = ResourceManager.GetObject("Activate_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Add_32 {
            get {
                object obj = ResourceManager.GetObject("Add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Admin_16 {
            get {
                object obj = ResourceManager.GetObject("Admin_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Admin_32 {
            get {
                object obj = ResourceManager.GetObject("Admin_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агент.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От кого:.
        /// </summary>
        public static string AgentPosition {
            get {
                return ResourceManager.GetString("AgentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Agents_32 {
            get {
                object obj = ResourceManager.GetObject("Agents_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AgentsOperations_16 {
            get {
                object obj = ResourceManager.GetObject("AgentsOperations_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AgentsOperations_32 {
            get {
                object obj = ResourceManager.GetObject("AgentsOperations_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По агентам.
        /// </summary>
        public static string AgentsQuota {
            get {
                return ResourceManager.GetString("AgentsQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возрастное ограничение.
        /// </summary>
        public static string AgeRestriction {
            get {
                return ResourceManager.GetString("AgeRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В других документах работающих с ценами есть не сохраненные данные. Сохраните их или обновите документы..
        /// </summary>
        public static string AnotherPriceEditDocumentIsEditedSaveOrRefresh {
            get {
                return ResourceManager.GetString("AnotherPriceEditDocumentIsEditedSaveOrRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap apply_template {
            get {
                object obj = ResourceManager.GetObject("apply_template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Cancel_32 {
            get {
                object obj = ResourceManager.GetObject("Cancel_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Change_32 {
            get {
                object obj = ResourceManager.GetObject("Change_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Check_16 {
            get {
                object obj = ResourceManager.GetObject("Check_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Check_32 {
            get {
                object obj = ResourceManager.GetObject("Check_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Check_All_32 {
            get {
                object obj = ResourceManager.GetObject("Check_All_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Comment_16 {
            get {
                object obj = ResourceManager.GetObject("Comment_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Comment_32 {
            get {
                object obj = ResourceManager.GetObject("Comment_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Console_16 {
            get {
                object obj = ResourceManager.GetObject("Console_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Console_32 {
            get {
                object obj = ResourceManager.GetObject("Console_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество:.
        /// </summary>
        public static string CountPosition {
            get {
                return ResourceManager.GetString("CountPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата:.
        /// </summary>
        public static string DatePosition {
            get {
                return ResourceManager.GetString("DatePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Deactivate_32 {
            get {
                object obj = ResourceManager.GetObject("Deactivate_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Delete_32 {
            get {
                object obj = ResourceManager.GetObject("Delete_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление мероприятия.
        /// </summary>
        public static string DeleteEvent {
            get {
                return ResourceManager.GetString("DeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить текущее мероприятие?.
        /// </summary>
        public static string DeleteEventConfirmation {
            get {
                return ResourceManager.GetString("DeleteEventConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Distribute_Table_32 {
            get {
                object obj = ResourceManager.GetObject("Distribute_Table_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Distribution_16 {
            get {
                object obj = ResourceManager.GetObject("Distribution_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Distribution_32 {
            get {
                object obj = ResourceManager.GetObject("Distribution_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Down_16 {
            get {
                object obj = ResourceManager.GetObject("Down_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Edit_32 {
            get {
                object obj = ResourceManager.GetObject("Edit_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не должно быть пустым.
        /// </summary>
        public static string EmptyFieldValidationRule {
            get {
                return ResourceManager.GetString("EmptyFieldValidationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания мероприятия.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маркер &quot;Итого&quot;.
        /// </summary>
        public static string EndTableMarker {
            get {
                return ResourceManager.GetString("EndTableMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колонка маркера.
        /// </summary>
        public static string EndTableMarkerColumn {
            get {
                return ResourceManager.GetString("EndTableMarkerColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Event_16 {
            get {
                object obj = ResourceManager.GetObject("Event_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Event_32 {
            get {
                object obj = ResourceManager.GetObject("Event_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите код.
        /// </summary>
        public static string EventCode {
            get {
                return ResourceManager.GetString("EventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите время окончания.
        /// </summary>
        public static string EventEndDate {
            get {
                return ResourceManager.GetString("EventEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите юр. лицо.
        /// </summary>
        public static string EventLegalEntity {
            get {
                return ResourceManager.GetString("EventLegalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название мероприятия.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мероприятие:.
        /// </summary>
        public static string EventPosition {
            get {
                return ResourceManager.GetString("EventPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Events_16 {
            get {
                object obj = ResourceManager.GetObject("Events_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Events_32 {
            get {
                object obj = ResourceManager.GetObject("Events_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите время начала.
        /// </summary>
        public static string EventStartDate {
            get {
                return ResourceManager.GetString("EventStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ExportToExcel_32 {
            get {
                object obj = ResourceManager.GetObject("ExportToExcel_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ExportToPdf_32 {
            get {
                object obj = ResourceManager.GetObject("ExportToPdf_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ExportToRtf_32 {
            get {
                object obj = ResourceManager.GetObject("ExportToRtf_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ExportToTxt_32 {
            get {
                object obj = ResourceManager.GetObject("ExportToTxt_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ExportToWord_32 {
            get {
                object obj = ResourceManager.GetObject("ExportToWord_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл сконвертирован некорректно.
        /// </summary>
        public static string File_Load_exception {
            get {
                return ResourceManager.GetString("File_Load_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл не распознан или в нём нет данных..
        /// </summary>
        public static string File_undefined {
            get {
                return ResourceManager.GetString("File_undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл не распознан или в нём нет данных:.
        /// </summary>
        public static string File_Undefined_Or_No_Data {
            get {
                return ResourceManager.GetString("File_Undefined_Or_No_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Родительный падеж.
        /// </summary>
        public static string Genitive {
            get {
                return ResourceManager.GetString("Genitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Give_32 {
            get {
                object obj = ResourceManager.GetObject("Give_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Group_Left_16 {
            get {
                object obj = ResourceManager.GetObject("Group_Left_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Group_Left_24 {
            get {
                object obj = ResourceManager.GetObject("Group_Left_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Group_Right_16 {
            get {
                object obj = ResourceManager.GetObject("Group_Right_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Group_Right_24 {
            get {
                object obj = ResourceManager.GetObject("Group_Right_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зал.
        /// </summary>
        public static string Hall {
            get {
                return ResourceManager.GetString("Hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Hall_32 {
            get {
                object obj = ResourceManager.GetObject("Hall_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индивидуальный предприниматель.
        /// </summary>
        public static string IndividualEntrepreneur {
            get {
                return ResourceManager.GetString("IndividualEntrepreneur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИНН.
        /// </summary>
        public static string INN {
            get {
                return ResourceManager.GetString("INN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только непроверенные.
        /// </summary>
        public static string IsNotOnlyUnchecked {
            get {
                return ResourceManager.GetString("IsNotOnlyUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только для выбранного агента.
        /// </summary>
        public static string IsOnlySelectedAgent {
            get {
                return ResourceManager.GetString("IsOnlySelectedAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IssueVoucher_16 {
            get {
                object obj = ResourceManager.GetObject("IssueVoucher_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IssueVoucher_32 {
            get {
                object obj = ResourceManager.GetObject("IssueVoucher_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КПП.
        /// </summary>
        public static string KPP {
            get {
                return ResourceManager.GetString("KPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Legal_entity_32 {
            get {
                object obj = ResourceManager.GetObject("Legal_entity_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юр. лицо.
        /// </summary>
        public static string LegalEntity {
            get {
                return ResourceManager.GetString("LegalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap List_Items_16 {
            get {
                object obj = ResourceManager.GetObject("List_Items_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap List_Items_32 {
            get {
                object obj = ResourceManager.GetObject("List_Items_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Load_16 {
            get {
                object obj = ResourceManager.GetObject("Load_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Load_32 {
            get {
                object obj = ResourceManager.GetObject("Load_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Load_Distribute_Voucher_32 {
            get {
                object obj = ResourceManager.GetObject("Load_Distribute_Voucher_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Load_Return_Voucher_32 {
            get {
                object obj = ResourceManager.GetObject("Load_Return_Voucher_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка документа....
        /// </summary>
        public static string LoadingDocument {
            get {
                return ResourceManager.GetString("LoadingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введён не правильный пароль.
        /// </summary>
        public static string MainDocument_AdminRoomExecute_Введён_не_правильный_пароль {
            get {
                return ResourceManager.GetString("MainDocument_AdminRoomExecute_Введён_не_правильный_пароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответственный менеджер.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Managers {
            get {
                object obj = ResourceManager.GetObject("Managers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Именительный падеж.
        /// </summary>
        public static string Nominative {
            get {
                return ResourceManager.GetString("Nominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОГРН.
        /// </summary>
        public static string OGRN {
            get {
                return ResourceManager.GetString("OGRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОГРНИП.
        /// </summary>
        public static string OGRNIP {
            get {
                return ResourceManager.GetString("OGRNIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действует на основании.
        /// </summary>
        public static string OnBasis {
            get {
                return ResourceManager.GetString("OnBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (%)процент.
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место проведения.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Place_32 {
            get {
                object obj = ResourceManager.GetObject("Place_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа мест проведения.
        /// </summary>
        public static string PlaceGroup {
            get {
                return ResourceManager.GetString("PlaceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PlaceGroup_32 {
            get {
                object obj = ResourceManager.GetObject("PlaceGroup_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место проведения:.
        /// </summary>
        public static string PlacePosition {
            get {
                return ResourceManager.GetString("PlacePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Положение в таблице.
        /// </summary>
        public static string PositionInTable {
            get {
                return ResourceManager.GetString("PositionInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Price_16 {
            get {
                object obj = ResourceManager.GetObject("Price_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Price_32 {
            get {
                object obj = ResourceManager.GetObject("Price_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена:.
        /// </summary>
        public static string PricePosition {
            get {
                return ResourceManager.GetString("PricePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PriceSchema_16 {
            get {
                object obj = ResourceManager.GetObject("PriceSchema_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PriceSchema_32 {
            get {
                object obj = ResourceManager.GetObject("PriceSchema_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Print_32 {
            get {
                object obj = ResourceManager.GetObject("Print_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организатор.
        /// </summary>
        public static string Promoter {
            get {
                return ResourceManager.GetString("Promoter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличить.
        /// </summary>
        public static string Raise {
            get {
                return ResourceManager.GetString("Raise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Re_Group_32 {
            get {
                object obj = ResourceManager.GetObject("Re_Group_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Redo_32 {
            get {
                object obj = ResourceManager.GetObject("Redo_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повтор....
        /// </summary>
        public static string RedoProgress {
            get {
                return ResourceManager.GetString("RedoProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уменьшить.
        /// </summary>
        public static string Reduce {
            get {
                return ResourceManager.GetString("Reduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Refresh_32 {
            get {
                object obj = ResourceManager.GetObject("Refresh_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Remove_From_Table_32 {
            get {
                object obj = ResourceManager.GetObject("Remove_From_Table_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В других документах работающих с ценами есть не сохраненные данные. Продолжить?.
        /// </summary>
        public static string RePriceSeatsDocument_ShowNotification {
            get {
                return ResourceManager.GetString("RePriceSeatsDocument_ShowNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to единиц.
        /// </summary>
        public static string RePriceViewModel_currency {
            get {
                return ResourceManager.GetString("RePriceViewModel_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Return_32 {
            get {
                object obj = ResourceManager.GetObject("Return_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Return_All_32 {
            get {
                object obj = ResourceManager.GetObject("Return_All_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ReturnVoucher_16 {
            get {
                object obj = ResourceManager.GetObject("ReturnVoucher_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ReturnVoucher_32 {
            get {
                object obj = ResourceManager.GetObject("ReturnVoucher_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Места из накладной не найдены на схеме.
        /// </summary>
        public static string ReturnVoucherLoadDocument_LoadSeatsFromReturnEvent_Места_из_накладной_не_найдены_на_схеме {
            get {
                return ResourceManager.GetString("ReturnVoucherLoadDocument_LoadSeatsFromReturnEvent_Места_из_накладной_не_найдены_" +
                        "на_схеме", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ряд:.
        /// </summary>
        public static string RowPosition {
            get {
                return ResourceManager.GetString("RowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Save_32 {
            get {
                object obj = ResourceManager.GetObject("Save_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Save_And_Accept_32 {
            get {
                object obj = ResourceManager.GetObject("Save_And_Accept_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение мероприятия.
        /// </summary>
        public static string SaveEvent {
            get {
                return ResourceManager.GetString("SaveEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения?.
        /// </summary>
        public static string SaveEventConfirmation {
            get {
                return ResourceManager.GetString("SaveEventConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Схема.
        /// </summary>
        public static string Scheme {
            get {
                return ResourceManager.GetString("Scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Схемы не существует.
        /// </summary>
        public static string Scheme_does_not_exist {
            get {
                return ResourceManager.GetString("Scheme_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во мест.
        /// </summary>
        public static string SeatCount {
            get {
                return ResourceManager.GetString("SeatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Места с:.
        /// </summary>
        public static string SeatFromPosition {
            get {
                return ResourceManager.GetString("SeatFromPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип мест:.
        /// </summary>
        public static string SeatGroupPosition {
            get {
                return ResourceManager.GetString("SeatGroupPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Места не найдены.
        /// </summary>
        public static string Seats_not_found {
            get {
                return ResourceManager.GetString("Seats_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Места из накладной не найдены на схеме.
        /// </summary>
        public static string Seats_not_found_on_scheme {
            get {
                return ResourceManager.GetString("Seats_not_found_on_scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Места по:.
        /// </summary>
        public static string SeatToPosition {
            get {
                return ResourceManager.GetString("SeatToPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сектор:.
        /// </summary>
        public static string SectorPosition {
            get {
                return ResourceManager.GetString("SectorPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите юридическое лицо.
        /// </summary>
        public static string SelectDefaultPromoterLegalEntity {
            get {
                return ResourceManager.GetString("SelectDefaultPromoterLegalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать агента.
        /// </summary>
        public static string SelectedAgentRequired {
            get {
                return ResourceManager.GetString("SelectedAgentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала мероприятия.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма:.
        /// </summary>
        public static string SumPricePosition {
            get {
                return ResourceManager.GetString("SumPricePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кому:.
        /// </summary>
        public static string SupplierPosition {
            get {
                return ResourceManager.GetString("SupplierPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Table_Link_16 {
            get {
                object obj = ResourceManager.GetObject("Table_Link_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Table_Link_32 {
            get {
                object obj = ResourceManager.GetObject("Table_Link_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TableSelectAll_32 {
            get {
                object obj = ResourceManager.GetObject("TableSelectAll_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TableSelectRow_32 {
            get {
                object obj = ResourceManager.GetObject("TableSelectRow_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap template {
            get {
                object obj = ResourceManager.GetObject("template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Templates_16 {
            get {
                object obj = ResourceManager.GetObject("Templates_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Templates_32 {
            get {
                object obj = ResourceManager.GetObject("Templates_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время:.
        /// </summary>
        public static string TimePosition {
            get {
                return ResourceManager.GetString("TimePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Существует неподтвержденная операция с этими местами. Подтвердите операции..
        /// </summary>
        public static string unaccepted_operation {
            get {
                return ResourceManager.GetString("unaccepted_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Undo_32 {
            get {
                object obj = ResourceManager.GetObject("Undo_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откат....
        /// </summary>
        public static string UndoProgress {
            get {
                return ResourceManager.GetString("UndoProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UniteDocuments_32 {
            get {
                object obj = ResourceManager.GetObject("UniteDocuments_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UniteDocuments_32_2 {
            get {
                object obj = ResourceManager.GetObject("UniteDocuments_32_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Up_16 {
            get {
                object obj = ResourceManager.GetObject("Up_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Up_161 {
            get {
                object obj = ResourceManager.GetObject("Up_161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Voucher_Operations_16 {
            get {
                object obj = ResourceManager.GetObject("Voucher_Operations_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Voucher_Operations_32 {
            get {
                object obj = ResourceManager.GetObject("Voucher_Operations_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операции с накладными.
        /// </summary>
        public static string VoucherOperations {
            get {
                return ResourceManager.GetString("VoucherOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблон накладной.
        /// </summary>
        public static string VoucherTemplate {
            get {
                return ResourceManager.GetString("VoucherTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать шаблон накладной.
        /// </summary>
        public static string VoucherTemplateRequired {
            get {
                return ResourceManager.GetString("VoucherTemplateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xml.
        /// </summary>
        public static string Xml_Extension_String {
            get {
                return ResourceManager.GetString("Xml_Extension_String", resourceCulture);
            }
        }
    }
}
