// <auto-generated />
namespace RedKassa.Promoter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class v_1_3_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v_1_3_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201407071043185_v_1_3_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
